// Generated by CoffeeScript 1.6.2
(function() {
  var Location, Locations, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Location = (function(_super) {
    __extends(Location, _super);

    function Location() {
      _ref = Location.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Location.prototype.defaults = {
      title: 'Put Title Here',
      author: 'Someone\'s Name goes here'
    };

    Location.prototype.url = '/places/add';

    return Location;

  })(Backbone.Model);

  Locations = (function(_super) {
    __extends(Locations, _super);

    function Locations() {
      _ref1 = Locations.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Locations.prototype.model = Location;

    Locations.prototype.url = 'places.json';

    Locations.prototype.initialize = function() {
      return this.on('add', function(model) {
        return alert('adding model');
      });
    };

    return Locations;

  })(Backbone.Collection);

}).call(this);
