// Generated by CoffeeScript 1.6.2
(function() {
  $(document).on('ready', function() {
    var countView, recentPlacesView;

    recentPlacesView = new PlacingLit.Views.RecentPlaces;
    return countView = new PlacingLit.Views.Countview;
  });

}).call(this);
