// Generated by CoffeeScript 1.6.2
(function() {
  $(document).on('ready', function() {
    var countView, hpmap, recentPlacesView;

    recentPlacesView = new PlacingLit.Views.RecentPlaces;
    countView = new PlacingLit.Views.Countview;
    return hpmap = new PlacingLit.Views.HomepagemapView;
  });

}).call(this);
