// Generated by CoffeeScript 1.6.2
(function() {
  $(document).on('ready', function() {
    var mapCanvas;

    console.log('ready');
    return mapCanvas = new PlacingLit.Views.MapCanvasView;
  });

}).call(this);
