// Generated by CoffeeScript 1.6.2
(function() {
  describe("Location Model", function() {
    it("should exist", function() {
      return expect(PlacingLit.Models.Location).toBeDefined();
    });
    return describe("Attributes", function() {
      var place;

      place = new PlacingLit.Models.Location;
      return it("should have default attributes", function() {
        expect(place.attributes.name).toBeDefined();
        return expect(place.attributes.title).toBeDefined();
      });
    });
  });

}).call(this);
