// Generated by CoffeeScript 1.6.2
(function() {
  var InfowindowView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InfowindowView = (function(_super) {
    __extends(InfowindowView, _super);

    function InfowindowView() {
      _ref = InfowindowView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    InfowindowView.prototype.template = _.template;

    '<% title %> by <% author %>';

    return InfowindowView;

  })(Backbone.View);

}).call(this);
