// Generated by CoffeeScript 1.6.2
(function() {
  var Countview, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Countview = (function(_super) {
    __extends(Countview, _super);

    function Countview() {
      _ref = Countview.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Countview.prototype.el = '#count';

    Countview.prototype.model = Location;

    Countview.prototype.count = null;

    Countview.prototype.initialize = function() {
      var locs,
        _this = this;

      locs = new Locations();
      locs.url = '/places/count';
      return locs.fetch({
        error: function(model, response) {
          return console.log('fetch error', error);
        },
        success: function(model, response) {
          _this.setCount(response.count);
          return _this.showCount();
        }
      });
    };

    Countview.prototype.setCount = function(count) {
      return this.count = count;
    };

    Countview.prototype.showCount = function() {
      return $(this.el).text(this.count + ' scenes have been mapped');
    };

    return Countview;

  })(Backbone.View);

}).call(this);
